"""Private file storage for evidence.

Local disk for development and the research prototype. The same interface can
be backed by S3-compatible storage for deployment (see docs/ARCHITECTURE.md §8).
"""

import hashlib
from pathlib import Path
from typing import BinaryIO

from app.core.config import get_settings


class LocalMediaStorage:
    def __init__(self, root: Path) -> None:
        self.root = root.resolve()

    def path(self, key: str) -> Path:
        path = (self.root / key).resolve()
        # Keys are generated by the server, but never allow escaping the root.
        if self.root not in path.parents:
            raise ValueError("Invalid storage key")
        return path

    def save(self, key: str, data: bytes) -> None:
        path = self.path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        temp = path.with_suffix(path.suffix + ".part")
        temp.write_bytes(data)
        temp.replace(path)

    def save_stream(self, key: str, source: BinaryIO) -> str:
        """Copy a file-like object into storage in chunks; returns its SHA-256."""
        path = self.path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        temp = path.with_suffix(path.suffix + ".part")
        digest = hashlib.sha256()
        with temp.open("wb") as out:
            while chunk := source.read(1024 * 1024):
                digest.update(chunk)
                out.write(chunk)
        temp.replace(path)
        return digest.hexdigest()

    def delete(self, key: str) -> None:
        self.path(key).unlink(missing_ok=True)


def get_storage() -> LocalMediaStorage:
    return LocalMediaStorage(get_settings().media_root)
