"""Idempotent report submission: reports.client_request_id.

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-30 13:21:59.019332
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reports", sa.Column("client_request_id", sa.Uuid(), nullable=True))
    op.create_unique_constraint(
        "uq_reports_client_request", "reports", ["reporter_id", "client_request_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_reports_client_request", "reports", type_="unique")
    op.drop_column("reports", "client_request_id")
    # ### end Alembic commands ###
