"""Reports, hazard types, per-year reference sequences and status history.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-30 13:15:07.027405
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from seeds.hazard_types import DEFAULT_HAZARD_TYPES

REPORT_STATUSES = ("submitted", "under_verification", "needs_clarification", "verified", "resolved")
# The status type is shared by two tables, so it is created once, explicitly.
report_status = postgresql.ENUM(*REPORT_STATUSES, name="report_status", create_type=False)


revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    report_status.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hazard_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hazard_types")),
        sa.UniqueConstraint("code", name=op.f("uq_hazard_types_code")),
    )
    op.create_table(
        "report_sequences",
        sa.Column("year", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("year", name=op.f("pk_report_sequences")),
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reference_no", sa.String(length=20), nullable=False),
        sa.Column("reporter_id", sa.Uuid(), nullable=False),
        sa.Column("hazard_type_id", sa.Integer(), nullable=False),
        sa.Column("other_hazard_text", sa.String(length=120), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("incident_date", sa.Date(), nullable=False),
        sa.Column("incident_time", sa.Time(), nullable=True),
        sa.Column("municipality", sa.String(length=80), nullable=False),
        sa.Column("province", sa.String(length=80), nullable=False),
        sa.Column("barangay_id", sa.Integer(), nullable=True),
        sa.Column("landmark", sa.String(length=200), nullable=True),
        sa.Column("location_text", sa.String(length=300), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("location_accuracy_m", sa.Integer(), nullable=True),
        sa.Column(
            "location_source",
            sa.Enum("gps", "map_pin", "manual", name="location_source"),
            nullable=True,
        ),
        sa.Column("status", report_status, nullable=False),
        sa.Column("verified_by_id", sa.Uuid(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_notes", sa.Text(), nullable=True),
        sa.Column("resolved_by_id", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("latitude BETWEEN -90 AND 90", name=op.f("ck_reports_latitude_range")),
        sa.CheckConstraint(
            "longitude BETWEEN -180 AND 180", name=op.f("ck_reports_longitude_range")
        ),
        sa.ForeignKeyConstraint(
            ["barangay_id"], ["barangays.id"], name=op.f("fk_reports_barangay_id_barangays")
        ),
        sa.ForeignKeyConstraint(
            ["hazard_type_id"],
            ["hazard_types.id"],
            name=op.f("fk_reports_hazard_type_id_hazard_types"),
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"], ["users.id"], name=op.f("fk_reports_reporter_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_id"], ["users.id"], name=op.f("fk_reports_resolved_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_id"], ["users.id"], name=op.f("fk_reports_verified_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint("reference_no", name=op.f("uq_reports_reference_no")),
    )
    op.create_index(op.f("ix_reports_barangay_id"), "reports", ["barangay_id"], unique=False)
    op.create_index(op.f("ix_reports_hazard_type_id"), "reports", ["hazard_type_id"], unique=False)
    op.create_index(op.f("ix_reports_reporter_id"), "reports", ["reporter_id"], unique=False)
    op.create_index(op.f("ix_reports_status"), "reports", ["status"], unique=False)
    op.create_index(op.f("ix_reports_submitted_at"), "reports", ["submitted_at"], unique=False)
    op.create_table(
        "report_status_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", report_status, nullable=True),
        sa.Column("to_status", report_status, nullable=False),
        sa.Column("changed_by_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_id"],
            ["users.id"],
            name=op.f("fk_report_status_history_changed_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
            name=op.f("fk_report_status_history_report_id_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_status_history")),
    )
    op.create_index(
        op.f("ix_report_status_history_report_id"),
        "report_status_history",
        ["report_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    hazard_types = sa.table(
        "hazard_types",
        sa.column("code", sa.String),
        sa.column("name", sa.String),
        sa.column("sort_order", sa.Integer),
        sa.column("is_active", sa.Boolean),
    )
    op.bulk_insert(
        hazard_types,
        [
            {"code": code, "name": name, "sort_order": index, "is_active": True}
            for index, (code, name) in enumerate(DEFAULT_HAZARD_TYPES)
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_report_status_history_report_id"), table_name="report_status_history")
    op.drop_table("report_status_history")
    op.drop_index(op.f("ix_reports_submitted_at"), table_name="reports")
    op.drop_index(op.f("ix_reports_status"), table_name="reports")
    op.drop_index(op.f("ix_reports_reporter_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_hazard_type_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_barangay_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_table("report_sequences")
    op.drop_table("hazard_types")
    # ### end Alembic commands ###
    report_status.drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="location_source").drop(op.get_bind(), checkfirst=True)
